<%@ Page Language="C#" MasterPageFile="~/admin.master" AutoEventWireup="true" CodeFile="capnhatqtri.aspx.cs" Inherits="Default3" Title="Cap nhat quan tri" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <span style="font-size: 24pt; color: black"><h1 align="center"><b>CẬP NHẬT QUẢN TRỊ</b></h1><br />
        <asp:SqlDataSource ID="DSND" runat="server" ProviderName="<%$ ConnectionStrings:MyDBConnectionString.ProviderName %>"
            ConnectionString="<%$ ConnectionStrings:MyDBConnectionString %>" SelectCommand="SELECT email, matkhau FROM tbluser WHERE (quyen = 'admin')"
            UpdateCommand="Update tblUser set MatKhau=@MatKhau where 
						email=@email" DeleteCommand="delete from tbluser where email=@email">
        </asp:SqlDataSource>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
            <ContentTemplate>
                <span style="font-size: 24pt; color: black">
                <span style="font-size: 12pt">
                    <asp:GridView ID="dgrDs" runat="server" AutoGenerateEditButton="True" DataKeyNames="email"
                        DataSourceID="DSND" AutoGenerateDeleteButton="True" Height="135px" Width="482px" ForeColor="black">
                    </asp:GridView>
                </span></span>
            </ContentTemplate>
        </asp:UpdatePanel>
    </span>
</asp:Content>
